In [1]:
print("Hello world")

Hello world


In [4]:
a = 10
b = 20 

c = a+b

print("Addition of A & B =",c)

Addition of A & B = 30


In [3]:
print("A","B","C",sep='\n')

A
B
C


In [1]:
a = ['a','b','e','d','c']
print(a.sort())

None


In [4]:
a = [1,2,3,4]
b = [4,6,7]
a.insert(2,6)
a


[1, 2, 6, 3, 4]

In [5]:
a.extend(b)
a

[1, 2, 6, 3, 4, 4, 6, 7]

In [7]:
a.reverse()
a

[7, 6, 4, 4, 3, 6, 2, 1]

In [12]:
a.remove(4)
a

[6, 4, 3, 6, 2]

In [14]:
a= tuple()
type(a)

tuple

In [17]:
a[1] = 1
a

TypeError: 'tuple' object does not support item assignment

In [20]:
a = (2,3,1,6,7,4)
sorted(a)

[1, 2, 3, 4, 6, 7]

In [21]:
s=set()
type(s)

set

In [33]:
    s = {()}

In [34]:
type(s)

set

In [46]:
s ={1,3,5,4,2,3,34,54,56,76,78}

In [36]:
s


{1, 2, 3, 4, 5}

In [55]:
s.pop()

78

In [50]:
s

{4, 5, 34, 54, 56, 76, 78}

In [65]:
s = {11,24,35,46,58,63,75,82}

In [68]:
s.pop()

75

In [69]:
s


{24, 46, 58, 63, 82}

In [1]:
d = ('name','age','gender')

In [2]:
dict.fromkeys(d)

{'name': None, 'age': None, 'gender': None}

In [6]:
a =0
s=0
while a<4:
    s +=a
    a +=1
print(s)

6


In [2]:
m = [7,9,11,2,4,6,145,456,1006,314,9648,789]

[ i**2 for i in m if i > 100]

[21025, 207936, 1012036, 98596, 93083904, 622521]

In [3]:
m = [7,9,11,2,4,6,145,456,1006,314,9648,789]
[ i**2 if i>100 else i**3 for i in m]

[343, 729, 1331, 8, 64, 216, 21025, 207936, 1012036, 98596, 93083904, 622521]

In [3]:
j = 5.5

if( j %5 == 0):
    print("Divisible by 5")
else:
    print("Not divisible by 5")

Not divisible by 5


In [4]:
j % 5

0.5

In [10]:
l1 = [1,2,3,4,5]
an = lambda x : x**2
an(2)

4

In [1]:
def num(*kwargs):
    return enumerate(*kwargs)
list(num(('123')))

[(0, '1'), (1, '2'), (2, '3')]

In [2]:
def func():
    print("You are welcome to func")
    print(var)
func()

You are welcome to func


NameError: name 'var' is not defined

In [3]:
def sqrt(num):
    num=0
    import math
    return math.sqrt(num)
sqrt(9)

0.0

In [7]:
arr = np.array(range(50,101))
arr
a = np.arange(50,101)
a

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
import numpy as np

In [20]:
b = np.random.random(5)
b

array([0.272224  , 0.67792791, 0.29298928, 0.93152562, 0.16060961])

In [21]:
c= np.random.randint(50)
c

19

In [13]:
c= np.random.randint(50,101,25)
c

array([55, 57, 74, 68, 97, 69, 50, 83, 77, 75, 95, 78, 95, 86, 73, 96, 61,
       87, 75, 80, 64, 82, 57, 55, 54])

In [22]:
c= np.random.randn(5)
c

array([-0.84182365, -2.42662911,  0.70097234, -1.68817245,  1.16224991])

In [17]:
st = np.array([['a','b','c'],['d','e','f']])
st

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [26]:
c= np.random.random(5)
c

array([0.24874507, 0.93631856, 0.47696479, 0.75769502, 0.20567791])

In [27]:
a =10 
print(type(a))

<class 'int'>


In [28]:
print('Hello')
print("Hello")

Hello
Hello


In [33]:
x = "Hello"[0]

In [30]:
x

'H'

In [34]:
v =  "  hello   "
v

'  hello   '

In [37]:
v.upper()

'  HELLO   '

In [38]:
v.replace("h","V")

'  Vello   '

In [39]:
a=10
b=20
print(a,b)

10 20


In [40]:
a,b=b,a

In [41]:
print(a,b)

20 10


In [42]:
a=b
b=a
print(a,b)

10 10


In [45]:
n=4

def f1():
    global n

    n=n**4

    print(n)

f1()

256


In [46]:
def func1():
    num=12
    def func2():
        nonlocal num
        num=7
    func2()
func1()
print(num)

NameError: name 'num' is not defined

In [48]:
n=3

def fun1():

    global n
    n=1

 

fun1()

print(n)

1


In [49]:
a = np.array([1,2,3,4,5])

b = np.arange(0,10,2)

c = a + b

print (c[4])

13


In [50]:
np.random.randint(1,0)

ValueError: low >= high

In [53]:
A=np.random.rand(12,3)
A

array([[0.95439756, 0.72014026, 0.30447795],
       [0.08792232, 0.28904176, 0.75622665],
       [0.91459085, 0.33269212, 0.20699801],
       [0.40129979, 0.19302803, 0.45967953],
       [0.03379902, 0.9564354 , 0.2522566 ],
       [0.25028636, 0.92090079, 0.06487265],
       [0.8290814 , 0.98656849, 0.87711938],
       [0.5921663 , 0.9680841 , 0.61449163],
       [0.60814281, 0.2266306 , 0.45177089],
       [0.19292942, 0.73550457, 0.16289858],
       [0.74068601, 0.4154878 , 0.31630855],
       [0.28427675, 0.06317338, 0.90276391]])

In [63]:
np.random.seed(seed=90)
np.random.randint(50,100,15)

array([77, 79, 81, 53, 89, 54, 87, 68, 60, 82, 93, 80, 66, 68, 63])

array([58, 74, 53, 89, 73, 65, 98, 60, 80, 84, 52, 84, 64, 84, 99])