In [4]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(1,-1)

In [3]:
a

array([], dtype=int32)

In [5]:
z = np.arange(4)

In [6]:
z>0

array([False,  True,  True,  True])

In [7]:
a = np.arange(15).reshape(3,5)
print(a.dtype.name)

int32


In [8]:
a = np.arange(1,5,20j)

In [9]:
a

array([], dtype=complex128)

In [10]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [11]:
list_1 = [[12,34,65],[66,45,77],[45,77,88]]
np.array(list_1)

array([[12, 34, 65],
       [66, 45, 77],
       [45, 77, 88]])

In [12]:
a = np.arange(5j,0,2)
a

array([], dtype=complex128)

In [15]:
d = np.array(([13,35,74,48],[23,37,37,38],[73,39,93,39]))
d[:,(1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])